#!/usr/bin/env python3
"""Generate every copy of the privacy policy from one source: legal/privacy.json.

There used to be two policies. The one on ahenora.com described email/password
accounts; the one inside the app did not, because it had been written when Google
sign-in was the only way in and nobody remembered to change both. Showing a user
a policy that does not describe what the app actually does is the kind of small
drift that becomes a real problem, so the copies are generated now and a test
(tests/test_legal_sync.py) fails if either is edited by hand.

    python scripts/build_legal.py            # rewrite both copies
    python scripts/build_legal.py --check    # fail if either is stale
"""
import argparse
import html
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# name -> (source json, ahenora.com copy, in-app screen, screen component name)
DOCS = {
    "privacy": ("legal/privacy.json", "docs/privacy.html",
                "frontend/app/privacy.tsx", "PrivacyScreen"),
    "terms": ("legal/terms.json", "docs/terms.html",
              "frontend/app/terms.tsx", "TermsScreen"),
}

def _banner_html(source):
    return f"<!-- Generated by scripts/build_legal.py from {source} — do not edit by hand. -->"


def _banner_tsx(source):
    return f"// Generated by scripts/build_legal.py from {source} — do not edit by hand."


def load(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as fh:
        return json.load(fh)


def _as_list(body):
    return body if isinstance(body, list) else [body]


def render_site(doc, name, source):
    out = [
        "<!doctype html>", '<html lang="en">', "<head>", _banner_html(source),
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f"<title>Ahenora — {html.escape(doc['title'])}</title>",
        "<style>",
        "  body { font-family: -apple-system, 'Segoe UI', Roboto, Arial, sans-serif; max-width: 760px; margin: 0 auto; padding: 40px 22px 80px; color: #1a1c24; line-height: 1.6; }",
        "  h1 { font-size: 30px; margin-bottom: 4px; }",
        "  .sub { color: #666; margin-bottom: 28px; }",
        "  h2 { font-size: 19px; margin-top: 32px; }",
        "  ul { padding-left: 20px; }",
        "  li { margin: 6px 0; }",
        "  a { color: #F56519; }",
        "  footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #888; font-size: 14px; }",
        "</style>", "</head>", "<body>",
        f"  <h1>Ahenora — {html.escape(doc['title'])}</h1>",
        f'  <div class="sub">Last updated: {html.escape(doc["updated"])}</div>',
        f"  <p>{html.escape(doc['intro'])}</p>",
    ]
    for section in doc["sections"]:
        out.append(f"  <h2>{html.escape(section['title'])}</h2>")
        items = _as_list(section["body"])
        if len(items) == 1:
            out.append(f"  <p>{html.escape(items[0])}</p>")
        else:
            out.append("  <ul>")
            out += [f"    <li>{html.escape(i)}</li>" for i in items]
            out.append("  </ul>")
    out += [
        f"  <footer>{html.escape(doc['footer'])} · "
        '<a href="/">Home</a> · ' + (
            '<a href="/terms.html">Terms &amp; Support</a>' if name == "privacy"
            else '<a href="/privacy.html">Privacy Policy</a>') + "</footer>",
        "</body>", "</html>", "",
    ]
    return "\n".join(out)


def _ts(value):
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render_app(doc, component, source):
    out = [
        _banner_tsx(source),
        "import React from 'react';",
        "import { LegalPage } from '../src/components/LegalPage';",
        "",
        f"export default function {component}() {{",
        "  return (",
        "    <LegalPage",
        f"      title={{{_ts(doc['title'])}}}",
        f"      subtitle={{{_ts(doc['subtitle'])}}}",
        f"      updatedAt={{{_ts(doc['updated'])}}}",
        "      sections={[",
    ]
    for section in doc["sections"]:
        out.append("        {")
        out.append(f"          title: {_ts(section['title'])},")
        items = _as_list(section["body"])
        if len(items) == 1:
            out.append(f"          body: {_ts(items[0])},")
        else:
            out.append("          body: [")
            out += [f"            {_ts(i)}," for i in items]
            out.append("          ],")
        out.append("        },")
    out += [
        "      ]}",
        f"      footer={{{_ts(doc['footer'])}}}",
        "    />",
        "  );",
        "}",
        "",
    ]
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if a copy is stale.")
    args = parser.parse_args()

    wanted = {}
    for name, (source, site, app, component) in DOCS.items():
        doc = load(source)
        wanted[os.path.join(ROOT, site)] = render_site(doc, name, source)
        wanted[os.path.join(ROOT, app)] = render_app(doc, component, source)
    stale = []
    for path, text in wanted.items():
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if current == text:
            continue
        stale.append(os.path.relpath(path, ROOT))
        if not args.check:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(text)
    if args.check and stale:
        print("Stale legal copies: " + ", ".join(stale))
        print("Run: python scripts/build_legal.py")
        return 1
    print(("Would rewrite: " if args.check else "Rewrote: ") + (", ".join(stale) or "nothing"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
