/**
 * Generates frontend/src/avatarArt.ts — the four house illustrations, as SVG.
 *
 * Run by hand when the recipes below change; the output is committed. The app
 * does NOT depend on DiceBear at runtime, which is the whole point: shipping
 * the library would pull every avatar style it ships into the bundle to use
 * one, and the art is what we want, not the generator.
 *
 *     cd scripts && npm i --no-save @dicebear/core@10 @dicebear/collection@9
 *     node gen_avatars.mjs
 *
 * Art: Avataaars by Pablo Stanley (https://avataaars.com), free for personal
 * and commercial use — no attribution required, unlike most of the other
 * DiceBear styles, which is why this one was chosen for a paid app.
 *
 * Skin tone is a single hex in the output, verified by generating two tones
 * and diffing: swapping the hex reproduces the other tone byte for byte. So
 * four drawings plus a string replace give all twenty combinations, instead of
 * twenty drawings at ~5KB each.
 */
import { writeFileSync } from 'node:fs';
import { createAvatar } from '@dicebear/core';
import { avataaars } from '@dicebear/collection';

const SKIN_TOKEN = '__SKIN__';
const SKIN_SEED = 'edb98a';   // replaced by the token below

// Shirt colours are the app's own accents, so a row of family faces reads as
// part of Ahenora rather than as clip art dropped into it.
const PEOPLE = {
  man:   { top: 'shortFlat',          hair: '724133', shirt: '2f5d57', clothing: 'shirtCrewNeck',  beard: true },
  woman: { top: 'longButNotTooLong',  hair: '724133', shirt: 'b4553f', clothing: 'blazerAndShirt', beard: false },
  boy:   { top: 'shortCurly',         hair: '724133', shirt: '3f6e9e', clothing: 'shirtCrewNeck',  beard: false },
  girl:  { top: 'straight02',         hair: '724133', shirt: '8a5ba6', clothing: 'shirtCrewNeck',  beard: false },
};

const draw = (who) => {
  const p = PEOPLE[who];
  const svg = createAvatar(avataaars, {
    seed: who,
    skinColor: [SKIN_SEED],
    top: [p.top],
    hairColor: [p.hair],
    facialHair: p.beard ? ['beardLight'] : [],
    facialHairProbability: p.beard ? 100 : 0,
    facialHairColor: [p.hair],
    clothing: [p.clothing],
    clothesColor: [p.shirt],
    eyes: ['happy'],
    eyebrows: ['defaultNatural'],
    mouth: ['smile'],
    accessoriesProbability: 0,
  }).toString();
  return svg
    // The metadata block is ~1.5KB of RDF per drawing and renders nothing.
    .replace(/<metadata[\s\S]*?<\/metadata>/, '')
    .replaceAll(SKIN_SEED, SKIN_TOKEN)
    .replaceAll(SKIN_SEED.toUpperCase(), SKIN_TOKEN);
};

const entries = Object.keys(PEOPLE)
  .map((who) => `  ${who}: ${JSON.stringify(draw(who))},`)
  .join('\n');

writeFileSync(
  new URL('../frontend/src/avatarArt.ts', import.meta.url),
  `// GENERATED by scripts/gen_avatars.mjs — do not edit by hand.
//
// Avataaars by Pablo Stanley (https://avataaars.com), free for personal and
// commercial use. Each drawing carries one skin colour, written here as the
// token ${SKIN_TOKEN} so a tone is a string replace rather than a fifth copy
// of the same picture.

export const SKIN_TOKEN = '${SKIN_TOKEN}';

export const AVATAR_ART: Record<string, string> = {
${entries}
};
`,
);
console.log('wrote frontend/src/avatarArt.ts');
